# /etc/keyd/default.conf
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Remaps the escape key to capslock
# esc = capslock

# Hold left alt to get vim-style arrows on hjkl
# other keys pass through for normal alt+ keybindings
leftalt = layer(nav)

[nav:A]
h = left
j = down
k = up
l = right
